---
install:
    - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.56.3/hugo_extended_0.56.3_Linux-64bit.deb
    - sudo dpkg -i /tmp/hugo.deb
    - npm install

script:
    - git submodule update --init --recursive
    - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  target_branch: gh-pages
  local_dir: docs
  on:
    branch: master
