baseURL = "https://vrm.dev/"
languageCode = "ja"
DefaultContentLanguage = "ja"
title = "VRM"
theme = "hyde"
publishDir = "docs"
hasCJKLanguage = true
enableEmoji = true

[params]
  description = "3D Humanoid Avatar format for VR"
  keywords = "VRM VR AR Avatar アバター 3D format フォーマット UniVRM"
  copyright = "VRM Consortium"

[menu]
  [[menu.main]]
    name = "└VRMについて"
    url = "/#vrmについて"
    weight = 1
  [[menu.main]]
    name = "└VRMフォーマット技術仕様"
    url = "/#vrmフォーマット技術仕様"
    weight = 2
  [[menu.main]]
    name = "└UniVRM仕様"
    url = "/#univrm-https-github-com-dwango-univrm-unity向けvrm標準実装-仕様"
    weight = 3
  [[menu.main]]
    name = "----"
    weight = 4
  [[menu.main]]
    name = "・UniVRM"
    url = "https://github.com/vrm-c/univrm"
    weight = 5
  [[menu.main]]
    name = "・VRMコンソーシアム"
    url = "https://www.vrm-consortium.org/"
    weight = 6
  
[Languages]
[Languages.ja]
[Languages.en]
