name: Deploy Github Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true          
    steps:
      - name: Checkout Source
        uses: actions/checkout@v1
      - name: Clone submodule
        run: git submodule update --init --recursive
      - name: npm install
        run: npm install
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.3.0
        with:
          # The Hugo version to download (if necessary) and use. Example: 0.58.2
          hugo-version: 0.74.3
          # Download (if necessary) and use Hugo extended version. Example: true
          extended: true
      - name: Build Hugo
        run: hugo -v
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
