name: Sphinx

on:
  push:
    branches:
      - sphinx
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt install gettext
      - run: pip install -r requirements.txt
      - name: sphinx build(ja)
        working-directory: ./content/ja/docs
        run: sphinx-build . ../../../public
      - name: sphinx build(en)
        working-directory: ./content/ja/docs
        run: sphinx-build . ../../../public/en -D language=en -A language=en
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
